### PR TITLE
Port GSDCHEM to WCOSS2

### PR DESCRIPTION
**Pull request by XianwuXue-NOAA**

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Comment by XianwuXue-NOAA** [comment]
@WalterKolczynski-NOAA After the merge, you will keep the branch, I just need change the commit ID to the merged ID in "FV3-GSDCHEM-WW3" repo, is it right?

**Comment by WalterKolczynski-NOAA** [comment]
Right. Whether I keep the branch is actually irrelevant if the commit is still somewhere in the repo, unless you are pointing to the branch.

**Review by WalterKolczynski-NOAA — COMMENTED** [review]
Is this going to break compilation on other machines?

**Comment by XianwuXue-NOAA** [comment]
Great. In "FV3-GSDCHEM-WW3" repo, it will change the commit id for the submodule for GSDCHEM.

**Comment by XianwuXue-NOAA** [comment]
I didn't test on other machines. This porting is only for WCOSS2 Transition. The changes for the options is recommended by Steven/NCO except we didn't use option "-fast-transcendentals" to keep precise on Prod

**Comment by WalterKolczynski-NOAA** [comment]
You need to make sure it still compiles elsewhere. Even though the current project is porting to WCOSS2, it needs to not break other machines. If you need to have special cases for WCOSS2, then you'll have to do a bit more work to treat WCOSS2 as a special case.

**Comment by XianwuXue-NOAA** [comment]
I tried to compile it on WCOSS_DELL and succeeded with modification for module files in "FV3-GSDCHEM-WW3" repo because I changed "module load $(CONFDIR)/modules.nems" to ". $(CONFDIR)/modules.nems" to make XX_ver use default value or passing value from build.ver.

**Comment by WalterKolczynski-NOAA** [comment]
What about Hera?

**Comment by XianwuXue-NOAA** [comment]
Succeeded after the similar modification of the module file in "FV3-GSDCHEM-WW3" repo

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Pull request merged**
